# poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: ollama
  max_new_tokens: 512
  context_window: 3900
  prompt_style: "llama3"

embedding:
  mode: ollama

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
